{
 "title": "Loki audit",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   {
    "name": "aggregation",
    "label": "Aggergation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "node", "label": "Node", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User logins per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user) (count_over_time(\n  {syslog=\"audit\",instance=~\"$node\"}\n  |= \"USER_START\"\n  | regexp \"acct=\\\"(?P<user>[^\\\"]+)\\\"\"\n[1h]))",
     "legendFormat": "{{user}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Audit types per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time(\n  {syslog=\"audit\",instance=~\"$node\"}\n  | pattern \"<type> <_>\"\n[1h]))",
     "legendFormat": "{{type}}",
     "resolution": 1
    }
   ]
  },
  { "title": "sudo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Sudo commands per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (for, real) (count_over_time({syslog=\"sudo\",instance=~\"$node\"}\n  |= \"session opened for\"\n  | regexp \"for user (?P<for>[^ ]*).* by (?P<real>.*)\"\n[$aggregation]))",
     "legendFormat": "{{real}} -> {{for}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Sudo commands by node per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({syslog=\"sudo\",instance=~\"$node\"}\n  |= \"session opened for\"\n[$aggregation]))",
     "legendFormat": "{{instance}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Latest root commands",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{syslog=\"sudo\",instance=~\"$node\"} |= \"USER=root\""
    }
   ]
  },
  {
   "title": "Latest non-root commands",
   "type": "logs",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{syslog=\"sudo\",instance=~\"$node\"} |= \"USER=\" != \"USER=root\""
    }
   ]
  },
  {
   "title": "Unauthorized sudo commands per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user) (count_over_time({syslog=\"sudo\",instance=~\"$node\"}\n  |~ \"incorrect password attempt\"\n  | regexp \"(?P<user>[^:]*) :\"\n[$aggregation]))",
     "legendFormat": "{{user}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Latest unauthorized commands",
   "type": "logs",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "{syslog=\"sudo\",instance=~\"$node\"} |~ \"incorrect password attempt|could not identify password\""
    }
   ]
  },
  { "title": "salt-minion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Salt commands by node per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({unit=\"salt-minion.service\",instance=~\"$node\"}\n  |= \"] Executing command\"\n[$aggregation]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salt commands per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cmd) (count_over_time({unit=\"salt-minion.service\",instance=~\"$node\"}\n  |= \"] Executing command\"\n  | regexp \"command (?P<cmd>.*) in directory\"\n[$aggregation]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  }
 ]
}