{
 "title": "Loki SSH",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   {
    "name": "aggregation",
    "label": "Aggergation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "node", "label": "Node", "query": "label_values(instance)" },
   {
    "name": "safeIP",
    "label": "Safe IPs",
    "query": "10\\\\..*|127.*|169.254.*|127.16\\\\..*|192.168.*"
   }
  ]
 },
 "panels": [
  {
   "title": "SSH logins from unknown IPs",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance,user,fingerprint,ip) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |~ \"Accepted (password|publickey)\"\n  !~ \"from ($safeIP) port\"\n  | regexp \"for (?P<user>.*) from (?P<ip>(.*)) port .* ssh.: (?P<type>[^ ]*) (?P<fingerprint>.*)\"\n  | regexp \"(?P<fingerprint>password) for (?P<user>.*) from (?P<ip>.*) port\"\n[$__range]))"
    }
   ]
  },
  {
   "title": "SSH logins from unknown IPs",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |~ \"Accepted (password|publickey)\"\n  !~ \"from ($safeIP) port\"\n  | regexp \"for (?P<user>.*) from (?P<ip>(.*)) port .* ssh.: (?P<type>[^ ]*) (?P<fingerprint>.*)\"\n  | regexp \"(?P<fingerprint>password) for (?P<user>.*) from (?P<ip>.*) port\"\n[$aggregation])",
     "legendFormat": "{{ip}} {{user}}@{{instance}} {{fingerprint}}"
    }
   ]
  },
  {
   "title": "SSH logins from safe IPs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (instance,user,fingerprint,ip) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |~ \"Accepted (password|publickey)\"\n  |~ \"from ($safeIP) port\"\n  | regexp \"for (?P<user>.*) from (?P<ip>(.*)) port .* ssh.: (?P<type>[^ ]*) (?P<fingerprint>.*)\"\n  | regexp \"(?P<fingerprint>password) for (?P<user>.*) from (?P<ip>.*) port\"\n[$__range]))"
    }
   ]
  },
  {
   "title": "Successful SSH logins per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, user) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |~ \"Accepted \"\n  | regexp \"for (?P<user>.*) from\"\n[$aggregation]))",
     "legendFormat": "{{user}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Failed SSH attempts per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, user) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"} |~ \"Failed \"[$aggregation]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSH logins by authorized keys",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (instance,user,fingerprint,ip) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |~ \"Accepted (password|publickey)\"\n  |~ \"from ($safeIP) port\"\n  | regexp \"for (?P<user>.*) from (?P<ip>(.*)) port .* ssh.: (?P<type>[^ ]*) (?P<fingerprint>.*)\"\n  | regexp \"(?P<fingerprint>password) for (?P<user>.*) from (?P<ip>.*) port\"\n[$__range]))"
    }
   ]
  },
  {
   "title": "Failed SSH attempts by source IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(500, sum by (ip,instance,user) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |= \"Failed password\"\n  | regexp \"for (?P<user>.*) from (?P<ip>.*) port\"[$__range])))"
    }
   ]
  },
  {
   "title": "Failed SSH attempts by user",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(500, sum by (ip,instance,user) (count_over_time({unit=\"sshd.service\",instance=~\"$node\"}\n  |= \"Failed password\"\n  | regexp \"for (?P<user>.*) from (?P<ip>.*) port\"[$__range])))"
    }
   ]
  }
 ]
}