{
 "title": "Nginx",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   { "name": "job", "query": "label_values(job)" },
   {
    "name": "aggregation",
    "label": "Aggergation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "node", "label": "Node", "query": "label_values(instance)" },
   { "name": "adhoc" },
   { "name": "grep" }
  ]
 },
 "panels": [
  {
   "title": "HTTP request by vhost per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (server) (count_over_time(\n  {job=\"$job\",instance=~\"$node\"}\n    |~ \"$grep\"\n  [$aggregation]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "HTTP request by status per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time(\n  {job=\"$job\",instance=~\"$node\"}\n    |~ \"$grep\"\n  [$aggregation]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Mean latency per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5,\n  {job=\"$job\",instance=~\"$node\"}\n    |~ \"$grep\"\n    | regexp \"request_time=(?P<request_time>[0-9.]*)\"\n    | unwrap request_time\n  [$aggregation]) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "95th latency percentile per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,\n  {job=\"$job\",instance=~\"$node\"}\n    |~ \"$grep\"\n    | regexp \"request_time=(?P<request_time>[0-9.]*)\"\n    | unwrap request_time\n  [$aggregation]) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of request per connection per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(server) (avg by (server,connection) (\n  count_over_time(\n    {job=\"$job\",instance=~\"$node\"}\n      |~ \"$grep\"\n      | regexp \"connection=(?P<connection>[0-9]+)\"\n    [$aggregation])))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Mean response size per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time (\n  {job=\"$job\",instance=~\"$node\"}\n    |~ \"$grep\"\n    | regexp \"size=(?P<size>[0-9]+)\"\n    | unwrap size\n  [$aggregation]) by(server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "HTTP access log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"$job\",instance=~\"$node\"} |~ \"$grep\"",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}