{
 "title": "Loki mail",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   {
    "name": "aggregation",
    "label": "Aggergation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Warning or higher",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{unit=~\"(dovecot|postfix).service\",level!=\"info\",instance=~\"$node\"}",
     "legendFormat": "{{user}}@{{instance}}:{{service}} <- {{ip}}"
    }
   ]
  },
  { "title": "MTA Postfix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Mail",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{unit=~\"postfix.service\",instance=~\"$node\"}\n  |~ \"(from|status)=\"\n  != \"reject:\"\n  | regexp \"(?P<msg_id>[^:]*)\"\n  | regexp \" to=<(?P<to>[^>]*)>.*status=(?P<status>[^ ]*) (?P<reason>.*)\"\n  | regexp \"orig_to=<(?P<orig_to>[^>]*)>\"\n  | regexp \"from=<(?P<from>[^>]*)>\"\n  | label_format to=\"{{.orig_to}} ({{.to}})\""
    }
   ]
  },
  {
   "title": "Rejected mails",
   "type": "logs",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "{unit=~\"postfix.service\",instance=~\"$node\"} |= \"reject:\"",
     "legendFormat": "{{user}}@{{instance}}:{{service}} <- {{ip}}"
    }
   ]
  },
  {
   "title": "Mails per $aggregation by sender",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (from) (count_over_time({unit=\"postfix.service\",instance=~\"$node\"}\n  |= \"from=\"\n  != \"reject:\"\n  | regexp \"from=<(?P<from>[^>]*)>\"[$aggregation]))",
     "legendFormat": "{{from}}"
    }
   ]
  },
  {
   "title": "Mails per $aggregation by recipient",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (to) (count_over_time({unit=\"postfix.service\",instance=~\"$node\"}\n  |= \"to=\"\n  != \"reject:\"\n  | regexp \" to=<(?P<to>[^>]*)>\"\n  | regexp \"orig_to=<(?P<orig_to>[^>]*)>\"\n  | label_format to=\"{{.orig_to}} ({{.to}})\"\n[$aggregation]))",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Mails per $aggregation by status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({unit=\"postfix.service\",instance=~\"$node\"} |= \"status=\" | logfmt\n[$aggregation]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by (status) (count_over_time({unit=\"postfix.service\",instance=~\"$node\"}\n  |= \"reject:\"\n  | regexp \"(?P<status>reject)\"[$aggregation]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({unit=\"postfix.service\",instance=~\"$node\"}\n  |= \"disconnect from\"\n  | regexp `(?P<name>[^ ]*)\\[(?P<ip>[^\\]])\\]`\n[$aggregation]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection per $aggregation",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(500, sum by (ip, name, instance) (count_over_time({unit=\"postfix.service\",instance=~\"$node\"}\n  |= \"disconnect from\"\n  | regexp `(?P<name>[^ ]*)\\[(?P<ip>[^\\]]*)\\]`[$__range])))"
    }
   ]
  },
  { "title": "MDA Dovecot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Successful logins per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, ip, user, instance) (count_over_time({unit=\"dovecot.service\",instance=~\"$node\"}\n  |= \"Login:\"\n  | regexp \"(?P<service>[^-]*).*user=<(?P<user>[^>]*)>.*rip=(?P<ip>[^,]*)\"[$aggregation]))",
     "legendFormat": "{{user}}@{{instance}}:{{service}} <- {{ip}}"
    }
   ]
  },
  {
   "title": "Pre-auth disconnection per $aggregation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, instance) (count_over_time({unit=\"dovecot.service\",instance=~\"$node\"}\n  |= \"no auth attempts\"\n  | regexp \"(?P<service>[^-]*).*rip=(?P<ip>[^,]*)\"\n[$aggregation]))",
     "legendFormat": "{{instance}}:{{service}}"
    }
   ]
  },
  {
   "title": "Pre-auth disconnection per $aggregation",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(500, sum by (service, ip, instance) (count_over_time({unit=\"dovecot.service\",instance=~\"$node\"}\n  |= \"no auth attempts\"\n  | regexp \"(?P<service>[^-]*).*rip=(?P<ip>[^,]*)\"[$__range])))"
    }
   ]
  }
 ]
}