{
 "title": "Mikrotik Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "loki", "query": "loki" },
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "device",
    "query": {
     "query": "label_values(mikrotik_system_uptime,name)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(mikrotik_interface_running,interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*rate(mikrotik_interface_rx_byte{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval]) > 0",
     "legendFormat": "Rx {{name}} {{interface}} {{comment}}"
    },
    {
     "expr": "-8*rate(mikrotik_interface_tx_byte{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval]) < 0",
     "legendFormat": "Tx {{name}} {{interface}} {{comment}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_system_cpu_load{name=~\"$device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - mikrotik_system_free_memory{name=~\"$device\"} / mikrotik_system_total_memory{name=~\"$device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HDD usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - mikrotik_system_free_hdd_space{name=~\"$device\"} / mikrotik_system_total_hdd_space{name=~\"$device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_system_uptime{name=~\"$device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Warning+",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{instance=~\"$device\"} |= `` | level != `informational` | level != `debug`"
    }
   ]
  },
  {
   "title": "Info",
   "type": "logs",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{instance=~\"$device\"} |= `` | level = `informational`"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "logs",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{instance=~\"$device\"} |= `` | level = `debug`"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mikrotik_interface_actual_mtu{name=~\"$device\", interface=~\"$interface\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "mikrotik_interface_link_downs{name=~\"$device\", interface=~\"$interface\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_rx_byte{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_tx_byte{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_rx_packet{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_tx_packet{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_tx_drop{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_rx_drop{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_rx_error{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "8*rate(mikrotik_interface_tx_error{name=~\"$device\", interface=~\"$interface\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "mikrotik_monitor_rate{name=~\"$device\", interface=~\"$interface\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "targets": [
      {
       "expr": "mikrotik_dhcp_leases_metrics{name=~\"$device\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}