{
 "title": "Node Exporter Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
    }
   },
   { "name": "fstype", "query": "ext.|(btr|x)fs|vfat" },
   { "name": "interfaces", "query": "(e|w).*" },
   { "name": "iodevs", "query": "[sh]d.|nvme.n.|mmcblk." },
   { "name": "system_mounts", "query": "/($|var)" }
  ]
 },
 "panels": [
  {
   "title": "Overall (Aggregated) Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Cores"
    },
    {
     "expr": "count(rate(node_cpu_seconds_total{mode=\"idle\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])<0.2)",
     "legendFormat": "Cores>80%"
    },
    {
     "expr": "sum(node_load1{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Load  Average (1m)"
    },
    {
     "expr": "sum(node_load5{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Load  Average (5m)"
    }
   ]
  },
  {
   "title": "Overall Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_Buffers_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Buf"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$node\"}-node_memory_MemFree_bytes{job=~\"$job\",instance=~\"$node\"}-node_memory_Cached_bytes{job=~\"$job\",instance=~\"$node\"}-node_memory_Buffers_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Use"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$node\"}-node_memory_SwapFree_bytes{job=~\"$job\",instance=~\"$node\"}-node_memory_SwapCached_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{job=~\"$job\",instance=~\"$node\"}/node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "Free% Average"
    }
   ]
  },
  {
   "title": "Overall Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"$interfaces\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*8)",
     "legendFormat": "Total RX Data (+)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"$interfaces\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*-8)",
     "legendFormat": "Total TX Data (-)"
    },
    {
     "expr": "sum(rate(node_network_receive_packets_total{device=~\"$interfaces\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Total RX Packets (+)"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{device=~\"$interfaces\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*-1)",
     "legendFormat": "Total TX Packets (-)"
    }
   ]
  },
  {
   "title": "Overall CPU Usage Breakdown",
   "type": "timeseries",
   "description": "N: Nice, U: User, S: System, I: IRQ, sI: SoftIRQ, St: Steal/Guest, IO: I/O wait",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (sum by (instance,cpu) (irate(node_cpu_seconds_total{mode!=\"idle\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"nice\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "N"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "U"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "S"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"irq\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "I"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"softirq\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "sI"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"steal\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "St"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "IO"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(smartmon_device_smart_available{instance=~\"$node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(smartmon_device_active{instance=~\"$node\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(smartmon_device_errors{instance=~\"$node\"})",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(smartmon_device_smart_healthy{instance=~\"$node\"}==0)",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "avg(avg(smartmon_attr_raw_value{name=\"temperature_celsius\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(smartmon_attr_raw_value{name=\"temperature_celsius\",instance=~\"$node\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Overall Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance,device))",
     "legendFormat": "Total Available"
    },
    {
     "expr": "sum(max(node_filesystem_size_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance,device)-max(node_filesystem_avail_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance,device))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "avg(avg(1-max(node_filesystem_avail_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance,device)/max(node_filesystem_size_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance,device)) by (instance))",
     "legendFormat": "Fill% Average"
    }
   ]
  },
  {
   "title": "Free system storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=~\"$job\",instance=~\"$node\",mountpoint=~\"$system_mounts\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Overall I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"$iodevs\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Total Read Data (+)"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$iodevs\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*-1)",
     "legendFormat": "Total Write Data (-)"
    },
    {
     "expr": "sum(rate(node_disk_reads_completed_total{device=~\"$iodevs\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Total Read OPS (+)"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{device=~\"$iodevs\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*-1)",
     "legendFormat": "Total Write OPS (-)"
    }
   ]
  },
  {
   "title": "Failed Systemd Units",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\",job=~\"$job\",instance=~\"$node\"} == 1"
    },
    {
     "expr": "node_systemd_service_restart_total{job=~\"$job\",instance=~\"$node\"} > 0"
    }
   ]
  },
  {
   "title": "Per Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Resources",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_load5{job=~\"$job\",instance=~\"$node\"}"
    },
    {
     "expr": "count(rate(node_cpu_seconds_total{mode=\"idle\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$node\"} / (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$node\"})))* 100"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"$interfaces\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"$interfaces\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"$iodevs\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$iodevs\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "100*max(1-node_filesystem_free_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}/node_filesystem_size_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=~\"$fstype\",job=~\"$job\",instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "sum(apt_upgrades_pending{job=~\"$job\",instance=~\"$node\"} or pacman_updates_pending{job=~\"$job\",instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\",instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "sum(node_scrape_collector_duration_seconds{job=~\"$job\",instance=~\"$node\"}) by (instance)"
    }
   ]
  }
 ]
}