{
 "title": "Power details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "psu",
    "label": "PSU",
    "query": {
     "query": "label_values(node_power_supply_info{job=~\"$job\",instance=~\"$host\"}, power_supply)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum without(power_supply) (node_power_supply_power_watt{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}) * sum without(power_supply) (node_power_supply_online{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"})",
     "legendFormat": "{{instance}} charge"
    },
    {
     "expr": "sum without(power_supply) (node_power_supply_power_watt{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}) * (sum without(power_supply) (node_power_supply_online{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"})-1)",
     "legendFormat": "{{instance}} drain"
    },
    {
     "expr": "-node_power_supply_current_ampere{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\",power_supply=~\".*[Bb][Aa][Tt].*\"} * node_power_supply_voltage_volt{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\",power_supply=~\".*[Bb][Aa][Tt].*\"}",
     "legendFormat": "{{instance}} {{power_supply}} drain"
    },
    {
     "expr": "node_power_supply_current_ampere{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\",power_supply!~\".*[Bb][Aa][Tt].*\"} * node_power_supply_voltage_volt{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\",power_supply!~\".*[Bb][Aa][Tt].*\"}",
     "legendFormat": "{{instance}} {{power_supply}} drain"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_power_supply_capacity{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "node_power_supply_energy_watthour{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}}"
    },
    {
     "expr": "node_power_supply_charge_ampere{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}} charge"
    }
   ]
  },
  {
   "title": "Active PSUs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_power_supply_present{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}} present"
    },
    {
     "expr": "node_power_supply_online{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}} online"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_power_supply_info{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}"
    }
   ]
  },
  {
   "title": "Wear and tear",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Charge cycles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_power_supply_cyclecount{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}}"
    }
   ]
  },
  {
   "title": "Health trend",
   "type": "timeseries",
   "description": "The energy/charge ratio between full and full_design",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_power_supply_energy_full{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"} /node_power_supply_energy_full_design{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}}"
    },
    {
     "expr": "node_power_supply_charge_full{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"} /node_power_supply_charge_full_design{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "node_power_supply_voltage_volt{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}}"
    },
    {
     "expr": "node_power_supply_voltage_min_design{job=~\"$job\",instance=~\"$host\",power_supply=~\"$psu\"}",
     "legendFormat": "{{instance}} {{power_supply}} min design"
    }
   ]
  }
 ]
}