{
 "title": "S.M.A.R.T. Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(smartmon_device_smart_available{job=~\"$job\",instance=~\"$host\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk failing self-test",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(1-smartmon_device_smart_healthy{job=~\"$job\",instance=~\"$host\",device=~\"$device\"} == 1, \"name\", \"fails self-test\", \"NO LABEL\", \".*\")"
    }
   ]
  },
  {
   "title": "Vulnerable disks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(smartmon_device_errors{job=~\"$job\",instance=~\"$host\",device=~\"$device\"} > 0, \"name\", \"error log entries\", \"NO LABEL\", \".*\")"
    },
    {
     "expr": "smartmon_attr_raw_value{name=~\"(fails self-test|error log entries|offline_uncorrectable|program_fail_count|current_pending_sector|reported_uncorrect|reallocated_sector_ct|reallocated_event_count|spin_retry_count|udma_crc_error_count|command_timeout)\",job=~\"$job\",instance=~\"$host\",device=~\"$device\"} > 0"
    }
   ]
  },
  {
   "title": "Raw S.M.A.R.T values",
   "type": "table",
   "description": "Green/red fields indicates pass-fails. They are self-test, empty error log and \"Critical attributes\" from https://en.wikipedia.org/wiki/S.M.A.R.T.#Known_ATA_S.M.A.R.T._attributes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartmon_device_info{job=~\"$job\",instance=~\"$host\",device=~\"$device\"}"
    },
    {
     "expr": "smartmon_attr_raw_value{job=~\"$job\",instance=~\"$host\",device=~\"$device\"}"
    },
    {
     "expr": "label_replace(smartmon_device_errors{job=~\"$job\",instance=~\"$host\",device=~\"$device\"}, \"name\", \"error log entries\", \"NO LABEL\", \".*\")"
    },
    {
     "expr": "label_replace(1-smartmon_device_smart_healthy{job=~\"$job\",instance=~\"$host\",device=~\"$device\"}, \"name\", \"fails self-test\", \"NO LABEL\", \".*\")"
    },
    {
     "expr": "label_replace(smartmon_device_active{job=~\"$job\",instance=~\"$host\",device=~\"$device\"}, \"name\", \"active\", \"NO LABEL\", \".*\")"
    }
   ]
  },
  { "title": "Wear and tear", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartmon_attr_raw_value{name=\"temperature_celsius\",job=~\"$job\",instance=~\"$host\",device=~\"$device\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "smartmon_attr_raw_value{name=\"power_on_hours\",job=~\"$job\",instance=~\"$host\",device=~\"$device\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Power cycles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartmon_attr_raw_value{name=\"power_cycle_count\",job=~\"$job\",instance=~\"$host\",device=~\"$device\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  }
 ]
}