{
 "title": "sensor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(mqtt_vcc, job)" } },
   {
    "name": "type",
    "query": {
     "query": "label_values(mqtt_vcc{job=~\"$job\",location=~\"$location\"},sensor_type)"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(mqtt_vcc{job=~\"$job\"},location)"
    }
   },
   { "name": "sample_window", "label": "sample_window", "query": "30m" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(location) (last_over_time(mqtt_temperature{location=~\"$location\", sensor_type=~\"$type\"}[$sample_window]))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(location) (last_over_time(mqtt_humidity{location=~\"$location\", sensor_type=~\"$type\"}[$sample_window]))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(location) (last_over_time(mqtt_temperature{location=~\"$location\", sensor_type=~\"$type\"}[$sample_window]))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(location) (last_over_time(mqtt_heat_index{location=~\"$location\", sensor_type=~\"$type\"}[$sample_window]))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg by(location) (last_over_time(mqtt_humidity{location=~\"$location\", sensor_type=~\"$type\"}[$sample_window]))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Sensor VCC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "last_over_time(mqtt_vcc{location=~\"$location\", sensor_type=~\"$type\"}[$sample_window])",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}